#faruad_Detectin_project

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
import os

In [6]:
(os.getcwd())
(os.listdir())

['.ipynb_checkpoints', 'Fraud_Detection_System.ipynb', 'paysim.csv']

In [7]:
df = pd.read_csv("paysim.csv", nrows=5)
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [8]:
df.shape

(5, 11)

In [10]:
df.dtypes

step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            5 non-null      int64
 1   type            5 non-null      object
 2   amount          5 non-null      float64
 3   nameOrig        5 non-null      object
 4   oldbalanceOrg   5 non-null      float64
 5   newbalanceOrig  5 non-null      float64
 6   nameDest        5 non-null      object
 7   oldbalanceDest  5 non-null      float64
 8   newbalanceDest  5 non-null      float64
 9   isFraud         5 non-null      int64
 10  isFlaggedFraud  5 non-null      int64
dtypes: float64(5), int64(3), object(3)
memory usage: 572.0+ bytes

In [13]:
df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,5.0,5.000000,5.000000,5.000000,5.00000,5.0,5.000000,5.0
mean,1.0,4746.812000,46660.200000,41913.388000,4236.40000,0.0,0.400000,0.0
std,0.0,5564.259778,71131.405889,67416.975901,9472.87838,0.0,0.547723,0.0
min,1.0,181.000000,181.000000,0.000000,0.00000,0.0,0.000000,0.0
25%,1.0,181.000000,181.000000,0.000000,0.00000,0.0,0.000000,0.0
50%,1.0,1864.280000,21249.000000,19384.720000,0.00000,0.0,0.000000,0.0
75%,1.0,9839.640000,41554.000000,29885.860000,0.00000,0.0,1.000000,0.0
max,1.0,11668.140000,170136.000000,160296.360000,21182.00000,0.0,1.000000,0.0

In [15]:
df = pd.read_csv("paysim.csv")

print("Dataset shape:", df.shape)

Dataset shape: (6362620, 11)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [17]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
(df["isFraud"].value_counts())

isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [20]:
(df["isFraud"].value_counts(normalize=True) * 100)

isFraud
0    99.870918
1     0.129082
Name: proportion, dtype: float64

In [21]:
df.groupby("type")["isFraud"].agg(["count", "sum"])

            count   sum
type
CASH_IN   1399284     0
CASH_OUT  2237500  4116
DEBIT       41432     0
PAYMENT   2151495     0
TRANSFER   532909  4097

In [22]:
fraud_rate = df.groupby("type")["isFraud"].mean() * 100

print(fraud_rate)

type
CASH_IN     0.000000
CASH_OUT    0.183955
DEBIT       0.000000
PAYMENT     0.000000
TRANSFER    0.768799
Name: isFraud, dtype: float64

In [24]:
(df.groupby("isFraud")["amount"].agg(["mean", "median", "max"]))

                 mean     median          max
isFraud
0        1.781970e+05   74684.72  92445516.64
1        1.467967e+06  441423.44  10000000.00

In [25]:
(df.groupby(["type", "isFraud"])["amount"]
      .agg(["mean", "median", "count"])
)

                          mean      median    count
type     isFraud
CASH_IN  0        1.689202e+05  143427.710  1399284
CASH_OUT 0        1.739172e+05  146946.560  2233384
         1        1.455103e+06  435516.905     4116
DEBIT    0        5.483665e+03    3048.990    41432
PAYMENT  0        1.305760e+04    9482.190  2151495
TRANSFER 0        9.062290e+05  486521.910   528812
         1        1.480892e+06  445705.760     4097

In [26]:
df["balance_change"] = df["oldbalanceOrg"] - df["newbalanceOrig"]

df["balance_error"] = (
    df["balance_change"] - df["amount"]
).abs()

print(df[["amount", "balance_change", "balance_error"]].head())

     amount  balance_change  balance_error
0   9839.64         9839.64   1.455192e-11
1   1864.28         1864.28   1.136868e-12
2    181.00          181.00   0.000000e+00
3    181.00          181.00   0.000000e+00
4  11668.14        11668.14   0.000000e+00

In [27]:
(df.groupby("isFraud")["balance_error"]
      .agg(["mean", "median", "max"])
)

                  mean    median          max
isFraud
0        201338.558304  69049.31  92445516.64
1         10692.325265      0.00  10000000.00

In [28]:
(df.groupby(["type", "isFraud"])["balance_error"]
      .agg(["mean", "median", "count"])
)

                           mean        median    count
type     isFraud
CASH_IN  0        337835.445783  2.868488e+05  1399284
CASH_OUT 0        147994.192850  1.198242e+05  2233384
         1          1306.125231  0.000000e+00     4116
DEBIT    0          1997.980422  2.955858e-12    41432
PAYMENT  0          6678.668482  3.807800e+02  2151495
TRANSFER 0        873050.622466  4.540331e+05   528812
         1         20122.054174  0.000000e+00     4097

In [29]:
(df.groupby(["type", "isFraud"])["balance_error"]
      .apply(lambda x: (x < 0.01).mean() * 100)
)

type      isFraud
CASH_IN   0           0.000000
CASH_OUT  0          10.883440
          1          99.416910
DEBIT     0          70.209017
PAYMENT   0          46.283305
TRANSFER  0           3.798136
          1          99.487430
Name: balance_error, dtype: float64

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

y_true = df["isFraud"]
y_pred = (df["balance_error"] < 0.01).astype(int)

(confusion_matrix(y_true, y_pred))
(classification_report(y_true, y_pred, zero_division=0))

'              precision    recall  f1-score   support\n\n           0       1.00      0.80      0.89   6354407\n           1       0.01      0.99      0.01      8213\n\n    accuracy                           0.80   6362620\n   macro avg       0.50      0.90      0.45   6362620\nweighted avg       1.00      0.80      0.89   6362620\n'

In [31]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

(cm)

array([[5066381, 1288026],
       [     45,    8168]])

In [32]:
mask = df["type"].isin(["CASH_OUT", "TRANSFER"])

y_true_filtered = df.loc[mask, "isFraud"]
y_pred_filtered = (
    (df.loc[mask, "balance_error"] < 0.01)
).astype(int)

(confusion_matrix(y_true_filtered, y_pred_filtered))
(classification_report(
    y_true_filtered, y_pred_filtered, zero_division=0
))

'              precision    recall  f1-score   support\n\n           0       1.00      0.90      0.95   2762196\n           1       0.03      0.99      0.06      8213\n\n    accuracy                           0.90   2770409\n   macro avg       0.52      0.95      0.50   2770409\nweighted avg       1.00      0.90      0.95   2770409\n'

In [33]:
df.groupby("isFraud")[
    ["amount", "oldbalanceOrg", "newbalanceOrig", "balance_change"]
].median()

            amount  oldbalanceOrg  newbalanceOrig  balance_change
isFraud
0         74684.72       14069.00             0.0            0.00
1        441423.44      438983.45             0.0       436317.49

In [34]:
selected_features = [
    "step",
    "type",
    "amount",
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest",
    "balance_error"
]

("Selected features:")
(selected_features)

("\nMissing values:")
(df[selected_features].isnull().sum())

step              0
type              0
amount            0
oldbalanceOrg     0
newbalanceOrig    0
oldbalanceDest    0
newbalanceDest    0
balance_error     0
dtype: int64

#جمع‌بندی تحلیل اکتشافی داده‌ها (EDA)

دیتاست PaySim :   شامل 6,362,620 تراکنش 
و 11 ستون اولیه است

. در بررسی اولیه، دادهٔ گمشده و ردیف تکراری مشاهده نشد.

#نتایج اصلی

حدود 99.87٪ تراکنش‌ها عادی و0.13٪ تقلبی هستند؛ بنابراین داده‌ها نامتوازن‌اند.
تمام تراکنش‌های تقلبی مشاهده‌شده از نوع CASH_OUT و TRANSFER
هستند.

میانهٔ مبلغ تراکنش‌های تقلبی از تراکنش‌های عادی بیشتر است

ویژگی‌های balance_change و balance_error برای بررسی تغییر موجودی ایجاد شدند.
قانون سادهٔ مبتنی بر balance_error، Recall بالایی داشت؛ 
اما هشدارهای کاذب زیادی تولید کرد.